/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bubble: typeof import('./src/components/Bubble/Bubble.vue')['default']
    BubbleList: typeof import('./src/components/BubbleList/BubbleList.vue')['default']
    BubbleList23: typeof import('./src/components/BubbleList/BubbleList23.vue')['default']
    Conversation: typeof import('./src/components/Conversation/Conversation.vue')['default']
    ConversationItem: typeof import('./src/components/Conversation/components/ConversationItem.vue')['default']
    Dropdown: typeof import('./src/components/Conversation/components/Dropdown.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Bubble/components/Loading.vue')['default']
    Sender: typeof import('./src/components/Sender/Sender.vue')['default']
    TestComp: typeof import('./src/components/TestComp/TestComp.vue')['default']
    Thinking: typeof import('./src/components/Thinking/Thinking.vue')['default']
    Welcome: typeof import('./src/components/Welcome/Welcome.vue')['default']
  }
}
